### ISSUE TITLE
NodeSDK支持Logger类

### ISSUE THREAD

**Issue by vnues** [tencent-connect/bot-node-sdk#62]
![31a12cdbfdee010a4adafb8ebfd802ca](https://user-images.githubusercontent.com/44258525/165479713-c7fb32c5-40c7-4fa3-bf99-f32b782db387.jpg)

**Comment by TimeBather** [comment]
Commit b3f3bc819795d019f23b4c1b0e402728a99d3fd4 已经修复此问题，待验证后关闭此Issue

**Comment by Joy-Wang** [comment]
建议已采纳，在新版本SDK中可以体验
